# .gitlab-ci.yml

image: node:14

stages:
  - build
  - deploy

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build

deploy:
  stage: deploy
  script:
    - apt-get update -yq && apt-get install -yq sshpass
    - sshpass -p "$SSH_PASSWORD" scp -r ./frontend/build/* $SSH_USER@$SSH_HOST:/var/www/html
  only:
    - master
